version: '3.8'  
  
services:  
  mesh2motion-prod:  
    build: .  
    ports:  
      - "3000:80"  
    restart: unless-stopped  
  
  mesh2motion-dev:  
    build:  
      context: .  
      dockerfile: Dockerfile.dev  
    ports:  
      - "5173:5173"  
    volumes:  
      - .:/app  
      - /app/node_modules  
    restart: unless-stopped  
    profiles:  
      - dev
